{{- range .Values.items }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ . }}
  labels:
    testing.argocd.argoproj.io/type: "stress"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  # TODOD why annotations not working
  #project: {{"'{{metadata.annotations.project}}'"}}
  project: {{ $.Values.spec.project }}
  source:
    repoURL: {{ $.Values.spec.source.repoURL }}
    # The cluster values field for each generator will be substituted here:
    targetRevision: {{ $.Values.spec.source.targetRevision }}
    path: {{ $.Values.spec.source.path }}
    helm:
      values: |
        name_prefix: {{ . }}
      {{- toYaml $.Values.spec.source.helm | nindent 6 }}
  destination:
    server: {{ $.Values.spec.destination.server }}
    namespace: {{ $.Values.spec.destination.namespace | default "default" }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
---
{{- end }}


