argoNamespace: ''

spec:
  source:
    repoURL: https://github.com/csantanapr/argocd-scaling-example.git
    path: apps/apps-per-cluster
    targetRevision: main
    helm:
      valueFiles: # Select number of ArgoCD Applications per Cluster
      #- values.yaml
      #- values-10.yaml
      - values-50.yaml
      #- values-100.yaml
      #- values-250.yaml
      #- values-500.yaml
      #- values-1000.yaml
      #- values-10000.yaml
  destination:
    namespace: default

labels:
  cloud: aws