apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ template "app.fullname" . }}
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  generators:
  - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      name: {{"'{{name}}-app'"}}
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      # TODOD why annotations not working
      #project: {{"'{{metadata.annotations.project}}'"}}
      project: default
      source:
        repoURL: {{ .Values.spec.source.repoURL }}
        # The cluster values field for each generator will be substituted here:
        targetRevision: {{ .Values.spec.source.targetRevision }}
        path: {{ .Values.spec.source.path }}
        helm:
        {{- toYaml .Values.spec.source.helm | nindent 10 }}
      destination:
        server: {{"'{{server}}'"}}
        namespace: {{ .Values.spec.destination.namespace | default "default" }}
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
