spec:
  project: tbd
  source:
    repoURL: https://github.com/csantanapr/argocd-scaling-example.git
    path: apps/configmaps-per-app
    targetRevision: main
    helm:
      valueFiles: # Select number of Configmaps per ArgoCD Application
      - values.yaml
      #- values-10.yaml
      #- values-100.yaml
      #- values-1000.yaml
      #- values-10000.yaml
  destination:
    namespace: default
    server: tbd

items:
- app-1
