argoNamespace: ''

spec:
  project: tbd
  source:
    repoURL: https://github.com/csantanapr/argocd-scaling-example.git
    path: apps/configmap
    targetRevision: main
    helm:
      valueFiles:
      #- values.yaml
      - values-10.yaml
      #- values-100.yaml
      #- values-1000.yaml
      #- values-10000.yaml
  destination:
    namespace: default
    server: tbd


items:
- app-1
- app-2
- app-3
- app-4
- app-5
- app-6
- app-7
- app-8
- app-9
- app-10
